[package]
name = "toy-payments-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
rust_decimal = "1.25"

[dependencies.serde]
version = "1.0"
features = ["derive"]

